version: '3.8'

services:
  bot:
    build: .
    container_name: os_lab5_bot
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BOT_TOKEN: ${BOT_TOKEN}
      ADMIN_ID: ${ADMIN_ID:-0}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped